<div class="row 200%">
							<div class="12u">

								<!-- Blog -->
									<section class="box blog">
										<h2 class="major"><span>Blog Oficial de Nicolás Romero</span></h2>
										<div>
											<div class="row">
												<div class="9u 12u(mobile)">
													<div class="content content-left">

														<!-- Featured Post -->
															<article class="box post">
																<header>
																	<h3><a href="#">Participar es tu derecho</a></h3>
																	<p>La inclusión de la sociedad es fundamental ...</p>
																	<ul class="meta">
																		<li class="icon fa-clock-o">Posteado hace 15 mins</li>
																		<li class="icon fa-comments"><a href="#">8</a></li>
																	</ul>
																</header>
																<a href="#" class="image featured"><img src="images/pic05.png" alt="" /></a>
																<p>
																	La inclusión de la sociedad es fundamental en el ejercicio de la democracia, es por ello que te invitamos a que participes en el Plan de Desarrollo Municipal 2016 - 2018
																	<br>
																	<br>
																	Envía tus propuestas de mejora, así como también los planes de acción para llevarlos a cabo; Juntos lograremos un municipio próspero, porque Nicolás Romero, Lo Merece Todo

																</p>
																<a href="#" class="button">Participa</a>
															</article>

													</div>
												</div>