<div class="row 200%">
							<div class="12u">

								<!-- Blog -->
									<section class="box blog">
										<!-- <h2 class="major"><span>Blog Oficial de Nicolás Romero</span></h2> -->
										<div>
											<div class="row">
												<div class="9u 12u(mobile)">
													<div class="content content-left">

														<!-- Featured Post -->
															<article class="box post">
																<header>
																	<h3><a href="#">INSCRIBETE A NUESTRA CARRERA-CAMINATA</a></h3>
																	<p>"EL AGUA ES VIDA" INSCRIPCIÓN GRATIS</p>
																	<!-- <ul class="meta">
																		<li class="icon fa-clock-o">Posteado hace 15 mins</li>
																		<li class="icon fa-comments"><a href="#">8</a></li>
																	</ul> -->
																</header>
																<a href="pdf/carrera.pdf" class="image featured"><img src="images/banner_carrera.png" alt="" /></a>
																<p>
																	DOMINGO 28 DE AGOSTO, 1ER CARRERA-CAMINATA "EL AGUA ES VIDA" 2016
																	<br> HABRÁ PREMIOS PARA EL PRIMER, SEGUNDO Y TERCER LUGAR. 
																	<br>
																	<br>
																	INFORMES: 5823.0991 / 5823.9133
																</p>
																<a href="pdf/carrera.pdf" class="button">Continuar leyendo..</a>
															</article>

													</div>
												</div>
											</div>
										</div>
									</section>
							</div>
</div>