						<div class="row 200%">
							<div class="12u">
							<!-- Features -->
									<section class="box features">
										<h2 class="major"><span>Oficinas</span></h2>
										<div>
											<div class="cuadroDir">
											<div class="cuadroDirChico">
												<a href="#"><img src="images/nada.png" alt="dif" class="imgDir1"></a>
												<h3><a href="#">DIF</a></h3>
<!-- 															<p>
																Desarrollo Integral de la Familia
															</p> -->
											</div>
											<div class="cuadroDirChico">
												<a href="#"><img src="images/nada.png" alt="imcufide" class="imgDir2"></a>
												<h3><a href="#">IMCUFIDE</a></h3>
<!-- 															<p>
																Instituto Municipal de Cultura Física y Deporte
															</p> -->
											</div>
											<div class="cuadroDirChico">
												<a href="#"><img src="images/nada.png" alt="sapasnir" class="imgDir3"></a>
												<h3><a href="#">SAPASNIR</a></h3>
<!-- 															<p>
																Sistema de Agua Potable Alcantarillado y Saneamiento de Nicolás Romero
															</p> -->
											</div>
											
											</div>
											<!-- <div class="row">
												<div class="12u">
													<ul class="actions">
														<li><a href="#" class="button big">Boton Uno</a></li>
														<li><a href="#" class="button alt big">Boton Dos</a></li>
													</ul>
												</div>
											</div> -->
										</div>
										
									</section>

							</div>
						</div>