						<div class="row 200%">
							<div class="12u">
							<!-- Features -->
									<section class="box features">
										<h2 class="major"><span>Sapasnir Oficinas de Recaudación Municipal</span></h2>
										<div>
											<div class="cuadroDir">
											<div class="cMapas">
												<div id="map-1" class="sMapa"></div></a>
												<h3>SAPASNIR 20 DE NOVIEMBRE</h3>
															<p>
																Av. 20 de Nov. 4,Centro,54400 Nicolás Romero, Méx.
															</p>
											</div>
											<div class="cMapas">
												<div id="map-2" class="sMapa"></div></a>
												<h3>SAPASNIR NICOLÁS ROMERO</h3>
															<p>
																Av. Nicolás Romero #52,Hidalgo,54400 Nicolás Romero, Méx.
															</p>
											</div>
											<div class="cMapas">
												<div id="map-3" class="sMapa"></div></a>
												<h3>SAPASNIR TOWN CENTER</h3>
															<p>
																Av. 20 de Nov. SN,Vista Hermosa,54414 Nicolás Romero, Méx.
															</p>
											</div>
											
											</div>
											<!-- <div class="row">
												<div class="12u">
													<ul class="actions">
														<li><a href="#" class="button big">Boton Uno</a></li>
														<li><a href="#" class="button alt big">Boton Dos</a></li>
													</ul>
												</div>
											</div> -->
										</div>
										
									</section>

							</div>
						</div>