
</div>
										</div>
									</section>

							</div>
						</div>
					</div>
				</div>
<!-- Footer -->
				<footer id="footer" class="container">
					<!-- <div class="row 200%">
						<div class="12u">

								<section>
									<h2 class="major"><span>Separador</span></h2>
									<p>
										Texto
									</p>
								</section>

						</div>
					</div> -->
					
					<div class="row 200%">
						<div class="12u">

							<!-- Contact -->
								<section>
									<h2 class="major"><span>Redes sociales</span></h2>
									<ul class="contact">
										<li><a class="icon fa-facebook" href="https://www.facebook.com/Sapasnir-254747391330107/"><span class="label">Facebook</span></a></li>
										<li><a class="icon fa-twitter" href="https://twitter.com/sapasnir"><span class="label">Twitter</span></a></li>
										<!-- <li><a class="icon fa-instagram" href="#"><span class="label">Instagram</span></a></li>
										<li><a class="icon fa-youtube" href="#"><span class="label">Youtube</span></a></li> -->
										<!-- <a href="https://play.google.com/store/apps/details?id=tv.periscope.android&hl=mx"><div class="periscope"></div></a> -->
										<!-- <li><a class="icon fa-google-plus" href="#"><span class="label">Google+</span></a></li> -->
									</ul>
								</section>

						</div>
					</div>


					<!-- Copyright -->
						<div id="copyright">
							<ul class="menu">
								<li>&copy; Todos los derechos reservados: SAPASNIR.MX </li><li>Creado por: <a href="http://www.nicolasromero.mx">H. Ayuntamiento de Nicolás Romero 2016 - 2018</a></li>
								<br>
								<p>Av. Nicolás Romero #52, Esquina con Hermenegildo Galeana, Colonia: Hidalgo ,C.P.: 54400 Nicolás Romero, Edo. Méx. Tel: 58-23-09-91 / 58-23-91-33</p>
							</ul>
						</div>

				</footer>

			</div>

		<!-- Scripts -->
			<script src="assets/js/jquery.min.js"></script>
			<script src="assets/js/jquery.dropotron.min.js"></script>
			<script src="assets/js/skel.min.js"></script>
			<script src="assets/js/skel-viewport.min.js"></script>
			<script src="assets/js/util.js"></script>
			<!--[if lte IE 8]><script src="assets/js/ie/respond.min.js"></script><![endif]-->
			<script src="assets/js/main.js"></script>
			<script type="text/javascript" src="assets/js/jquery.cycle2.js"></script>


			<script src="https://maps.googleapis.com/maps/api/js?language=es"></script>
			<script type="text/javascript" src="assets/js/easymap.plugin.js"></script>
			<script type="text/javascript" src="assets/js/script.js"></script>
			<script type="text/javascript" src="assets/js/google.js"></script>


		
</body>
</html>