					<div class="container">
						<div class="row 200%">
							<div class="12u">
							<!-- Features -->
									<section class="box features">
										<h2 class="major"><span>Sitios de Interés</span></h2>
										<div class="cuadroInteres">
											<div class="cuadroIntChico">
												<div class="cuadroIntX">
												<a href="http://www.presidencia.gob.mx">
													<div class="cuadroIntimg" id="gobmx"></div>
													<div class="cuadroInttxt"><h6>Presidencia de la República</h6></div>
												</a>
												</div>
												<div class="cuadroIntX">
												<a href="http://edomex.gob.mx">
													<div class="cuadroIntimg" id="edomex"></div>
													<div class="cuadroInttxt"><h6>Gobierno del Estado de México</h6></div>
												</a>
												</div>
												
												<!-- <div class="cuadroIntX">
												<a href="conac.php">
													<div class="cuadroIntimg" id="conac2"></div>
													<div class="cuadroInttxt"><h6>CONAC</h6></div>
												</a>
												</div> -->
												<br>
												<br>

												<!-- links de transparencia -->

												<div class="cuadroIntX">
												<a href="http://www.infoem.org.mx">
													<div class="cuadroIntimg2" id="infoem"></div>
													<div class="cuadroInttxt2"><h6>infoem</h6></div>
												</a>
												</div>
												<div class="cuadroIntX">
												<a href="http://www.saimex.org.mx/saimex/ciudadano/login.page">
													<div class="cuadroIntimg2" id="saimex"></div>
													<div class="cuadroInttxt2"><h6>SAIMEX</h6></div>
												</a>
												</div>
												<!-- <div class="cuadroIntX">
												<a href="#">
													<div class="cuadroIntimg2" id="conac"></div>
													<div class="cuadroInttxt2"><h6>CONAC</h6></div>
												</a>
												</div> -->
												<!-- <div class="cuadroIntX">
												<a href="http://www.ipomex.org.mx/ipo/portal/nicolasromero.web">
													<div class="cuadroIntimg2" id="ipomex"></div>
													<div class="cuadroInttxt2"><h6>ipomex</h6></div>
												</a>
												</div> -->

											</div>
										</div>
									</section>

							</div>
						</div>
					</div>