<!-- Main -->
				<div id="main-wrapper">
					<div id="main" class="container">
						<div class="row 200%">
							<div class="12u">

								<!-- Highlight -->
									<section class="box highlight">
										<ul class="special">
											<li><a href="telEmergencia.php" class="icon fa-phone"><span class="label1">Números de Atención</span></a></li>
											<li><a href="https://www.facebook.com/Sapasnir-254747391330107/" class="icon fa-thumbs-o-up"><span class="label1">#Trabajo y Resultados</span></a></li>
											<li><a href="mail.php" class="icon fa-envelope"><span class="label1">Correo Institucional</span></a></li>
										</ul>
										<!-- <header>
											<h2>Título del Artículo</h2>
											<p>Subtitulo del Artículo</p>
										</header>
										<p>
											Texto del Artículo
										</p> -->
									</section>

							</div>
						</div>