			<!-- Nav -->
				<nav id="nav">
					<ul>
						<li class="current"><a href="index.php">Inicio</a></li>
						<li><a href="#">Directorio</a></li>
						<li><a href="#">Trámites y Servicios</a>
							<ul>
								<li><a href="#">Aviso de Pago</a></li>
								<li><a href="#">Pagos en Linea</a></li>
							</ul>
						</li>

						<li><a href="#">Cultura del Agua</a></li>
						<li><a href="http://www.ipomex.org.mx/ipo/portal/nicolasromero.web">Transparencia</a></li>
						<li><a href="#">Contacto</a></li>
					</ul>
				</nav>