			<!-- Nav -->
				<nav id="nav">
					<ul>
						<li class="current"><a href="index.php">Inicio</a></li>
						<li><a href="#">¿Quiénes Somos?</a>
							<ul>
								<li><a href="#">Directorio</a></li>
								<li><a href="organigrama.php">Organigrama</a></li>
							</ul>
						</li>

						<li><a href="#">Trámites y Servicios</a>
							<ul>
								<li><a href="#">Aviso de Pago</a></li>
								<li><a href="#">Pagos en Linea</a></li>
								<li><a href="tarifas.php">Tarifas 2016</a></li>
							</ul>
						</li>

						<li><a href="#">Cultura del Agua</a></li>
						<li><a href="#">Transparencia</a></li>
						<li><a href="#">Contacto</a></li>
					</ul>
				</nav>